name: adiaha_tv
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  provider: ^4.3.2+1
  get: ^3.5.1
  flutter_svg: ^0.18.1
  carousel_slider: ^2.2.1
  video_player: ^0.10.12+2
  flick_video_player: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/dummy/
  fonts:
    - family: CeraPro
      fonts:
        - asset: assets/fonts/CeraProMedium.otf
        - asset: assets/fonts/CeraProLight.otf
        - asset: assets/fonts/CeraProBold.otf
          weight: 500
